# Generated by Django 4.2.7 on 2023-12-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_dashboard', '0002_powermeter_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermeter',
            name='voltage',
            field=models.FloatField(default=0, null=True),
        ),
    ]
